spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/erp
    username: postgres
    password: postgres
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


