spring:
  application:
    name: market-api

server:
  port: 8085

eureka:
  instance:
    prefer-ip-address: true

resilience4j:
  retry:
    instances:
      profile-in-yml-file:
        max-attempts: 5 #by default resilience4j will try 3 times
        wait-duration: 2s
        enable-exponential-backoff: true
