spring:
  application:
    name: market-api

server:
  port: 8085

eureka:
  instance:
    prefer-ip-address: true

resilience4j:
  bulkhead:
    instances:
      profile-in-yml-file:
        max-concurrent-calls: 2 #max-concurrence-requests-that-end-point-annotated-with-this-profile-will-agree
  ratelimiter:
    instances:
      profile-in-yml-file:
        limit-for-period: 2 #max requests in limit-refresh-period
        limit-refresh-period: 10s #period-for-wait
  retry:
    instances:
      profile-in-yml-file:
        max-attempts: 5 #by default resilience4j will try 3 times
        wait-duration: 2s
        enable-exponential-backoff: true
