spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/erp
    username: postgres
    password: postgres
  sleuth:
    sampler:
      probability: 1.0
  #zipkin:
    #base-url: http://localhost:9411 #http://localhost:9411 is default zipkin url, change this property to send logs other zipkin url

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


